name: "Backend workflow"
on: 
  workflow_call:
    inputs:
      environments:
        required: true
        type: string
  #push:
    #paths: backend/**

jobs:
  greet_from_main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run code
        run: echo "Hello world from ${{ inputs.environments }}"

      - name: show file contents
        run: cat ${{ inputs.environments }}/hello.txt
