name: "Frontend workflow"
on: 
  push:
    paths: frontend/**

jobs:
  greet_from_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run code
        run: echo "Hello world from Frontend"

      - name: show file contents
        run: cat frontend/hello.txt
