name: reusable-workflow
on:
  push:
    branches: main

jobs:
  reusable_workflow-backend:
    uses: ./.github/workflows/backend.yml
    with:
      environments: backend

  reusable_workflow_frontend:
    uses: ./.github/workflows/backend.yml
    with:
      environments: frontend

  
